name: Typedoc

on:
  push:
    branches:
      - master  # Set a branch name to trigger deployment
      - typedoc-action

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Use Node.js
        uses: actions/setup-node@v1

      - name: Install
        env:
          RUNNING_NODE_CI: 1
        run: npm ci

      - name: Build
        run: npm run build

      - name: Generate
        run: npm run doc:generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ref
          destination_dir: ./ref
          keep_files: true
